version: 2
jobs:
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm run test:coverage
            ./cc-test-reporter after-build -t lcov -p coverage --exit-code $?
            npx codecov
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build 
          command: |
            npm run build
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCLOUD_KEY_JSON > /home/circleci/.gcloud-key
            gcloud auth activate-service-account --key-file=/home/circleci/.gcloud-key
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud config set project e-sports-info
            gcloud app deploy

workflows:
  version: 2
  release:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - test
            - deploy
          filters:
            branches:
              only: master