version: 2
jobs:
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Setup CodeCov
          command: |
            npm install codecov -g
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm run test:coverage
            ./cc-test-reporter after-build -t lcov -p coverage --exit-code $?
            codecov

workflows:
  version: 2
  release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master